### ISSUE TITLE
Consuming from Kafka topic

### ISSUE THREAD

**Issue by Rap70r** [AbsaOSS/ABRiS#102]
Hello,

I have a setup in EMR where I'm consuming from a kafka topic using spark structured streaming in batches. I noticed in the logs there is a repeated message between the beginning and the end of the stage of each cycle.
The message is: 
> Creating adapter for strategy: topic.name

This message gets repeated and then there is a gap in the log time just when the cycle is done and the following message is displayed:

> Executor: Finished task #.# in stage ##.#. #### bytes result sent to driver

My goal is to tune up the performance of extracting from a kafka topic. And the time gap between the beginning and the end of that message is what takes the longest.
Can you please explain to me what is happening when that message is repeated?
Also, what are some techniques to tune up the performance of the consumer when there is a schema registry running with avro format?

Thank you

**Comment by cerveada** [comment]
Hello,
unfortunately I don't have time right now to analyse what exactly happens. I guess it could be the communication with schema registry. As a test you could try to provide the schema for Abris externally and see how it changes the performance. Other way could be to debug / profile the code to find out what happens exactly.

**Comment by cerveada** [comment]
Hi, 
new version of Abris 2.3.0 was released - it may help with your problems.

**Comment by Rap70r** [comment]
Hello cerveada,

I'll try that. Do you mean 3.2.0?

Thank you

**Comment by cerveada** [comment]
Ah, yes 3.2.0 Sorry
