### ISSUE TITLE
Thread safe schemamanager

### ISSUE THREAD

**Issue by lyogev** [AbsaOSS/ABRiS#109]
Hi!
I noticed that ```SchemaManager.scala``` is static.
I want to be able to consume with multiple threads, would you consider making ```schemaRegistryClient``` a ```DynamicVariable```?
Thanks

**Comment by lyogev** [comment]
Maybe I can provide some context, I want to start a multi threaded consuming in spark (FAIR scheduler) from multiple topics, but I'm getting errors, I guessed it's related to the fact that schemamanager is a static object, therefore it can't hold more than a single configuration (therefore topic).

**Comment by felipemmelo** [comment]
Hi @lyogev ,

That is a very unique use case, thanks for sharing :)

May I ask you to share the errors you're getting?

Also, checking if I got it correctly, you'll launch Kafka consumers from inside executors and these consumers will be tailing different topics, is it? If not, could you also share some snippets of your code that show the critical parts requiring a thread-safe `SchemaManager`?

**Comment by lyogev** [comment]
Thanks @felipemmelo !
So I've been working on this PR:
https://github.com/YotpoLtd/metorikku/pull/310/files

Basically I want to add the ability to run multiple jobs under the same process with the FAIR scheduler, utilising the cluster better in cases where the jobs have a meaning together.
To do that I wrapped all the jobs in threads.

The error I'm getting is:
```org.apache.avro.AvroTypeException: Found SOME_TOPIC.Value, expecting union```

I figured it's due to the fact that when I setup abris it actually overwrites the last configuration so it overwriting the topic for example to all other threads.

**Comment by felipemmelo** [comment]
Hi @lyogev , got you, thanks.

Before we go any further, maybe something like this would solve?

    val tlDf = new ThreadLocal[DataFrame] {
      override def initialValue(): DataFrame = {
        import za.co.absa.abris.avro.functions.from_confluent_avro
        val decoder = from_confluent_avro(col("value"), schemaRegistryConfig)
        dataFrame.select(decoder as 'data)
      }
    }
    tlDf
      .get()
      .where( ... ) // your original code comes here

That should give you a unique, thread-safe local instance of `SchemaManager` since the API would be invoked through a `val` inside a `ThreadLocal`. 

**I have not tried it myself**, though, so maybe if you can and it works we can add to the documentation.

**Comment by lyogev** [comment]
Cool idea. I'll give it a try.Thanks!

**Comment by felipemmelo** [comment]
Hi @lyogev , any success?

**Comment by lyogev** [comment]
Hi! No it didn’t work....

**Comment by felipemmelo** [comment]
That is a shame. @cerveada and myself have discussed this and we'll be changing `SchemaManager` to a class, as you suggested.

**Comment by lyogev** [comment]
Thanks @felipemmelo!

**Comment by lyogev** [comment]
I saw #112 can I try now?! :)

**Comment by cerveada** [comment]
Hi, You can try, but you have to build it from source code. It's not released yet. The release will most probably happen this week.

**Comment by lyogev** [comment]
Awesome! I'll give it a try

**Comment by cerveada** [comment]
Hi, the version 3.2.0 was released. It should be fixed there, could you try it and let us know if it's working well?

**Comment by lyogev** [comment]
It's not working for me just like that, any changes I need to make in terms of the API?

**Comment by lyogev** [comment]
I'm getting:
```Caused by: org.apache.avro.AvroTypeException: Found topic1.Value, expecting union```

**Comment by lyogev** [comment]
My bad. still testing

**Comment by cerveada** [comment]
Since there seems to be no issue any more, I'm closing this ticket. Please open a new one if you have any problems.

**Comment by lyogev** [comment]
Really sorry for not writing back, my tests were not successful and I had a very busy week.
However I think it works now and I need to fix other things to make my PR work.
Thanks a lot for handling this and thanks for Abris!
