### ISSUE TITLE
please publish for scala version

### ISSUE THREAD

**Issue by koertkuipers** [AbsaOSS/ABRiS#11]
i would expect the dependency to be:
organization za.co.absa
package abris_2.11
version 2.0.0

and artifact pom path for example:
za/co/absa/abris_2.11/2.0.0/abris_2.11-2.0.0.pom

soon spark will be published for scala 2.11 and scala 2.12 and then the current scheme of not appending scala version will become an issue.

thanks!
koert

**Comment by felipemmelo** [comment]
Hi Koert, very good point, have just done it. 

It may take a couple of hours for the new version to be available at Maven Central but it is already published at Nexus. 

Thanks a lot for the suggestion.
