### ISSUE TITLE
Any plan for upgrade to Spark 2.4.6 and 3.0.0-preview2

### ISSUE THREAD

**Issue by omidb** [AbsaOSS/ABRiS#122]
Hi,

I tried to use the library with 2.4.6 and 3.0.0 and it's not easy to make it work. many incompatibilities. Any plan for an upgrade?

Thanks

**Comment by cerveada** [comment]
Hello,
yes plan is to support all 2.4.x versions and eventually 3.0.0 as well, but it may take some time, since I have other stuff to work on.

What issues do you have with 2.4.6? You may be able to override the dependencies from Abris by declaring them in your project.

**Comment by omidb** [comment]
Yes, it's just not smooth. Thanks for maintaining the library.
