### ISSUE TITLE
Schema Registry Client created on every Spark's task

### ISSUE THREAD

**Issue by Strabox** [AbsaOSS/ABRiS#135]
Before everything kudos for this library is pretty pretty cool and does a very good job.

As far as I understood the code and from my knowledge about Apache Spark execution model the functions to_avro e from_avro from this library will create the Schema Registry clients (when using confluent version of the functions) in every task instead of caching the reference for the object to be reutilized by the Spark's Executor JVM in future jobs/tasks.

I understand that for batch jobs it doesn't matter but in my use case which is a streaming one with fixed number of executors 24/7 I would like to not pay the price of constantly creating Schema Registry clients that will download the schema in every Spark's task.

It is possible to contribute with such solution?

**Comment by cerveada** [comment]
Yes I'm aware of this problem. It could be solved by adding map to SchemaManagerFactory holding one instance of RegistryClient per client configuration.

I am not sure from your question, but if you want to contribute we will be really happy.

**Comment by cerveada** [comment]
Great! No rules, just keep the formatting consistent with the rest of the project. Yes, fork master and do a pull request.

**Comment by cerveada** [comment]
Yes, but version 4.x.x handles schema downloading even more effectively.
