### ISSUE TITLE
"topic.record.name" in scala spark schema registry integration

### ISSUE THREAD

**Issue by leviaz** [AbsaOSS/ABRiS#138]
Hello, I'm having trouble implementing the spark + schema registry integration using key and value.
The documentation is not very clear, what is "topic.record.name"?
Could you send me a real example of usage? only with "foo" and "com.example" I'm not able to understand what does really means the code.

**Comment by cerveada** [comment]
Hi,
this is not really defined by Abris - it's confluent schema registry subject name strategy and it's defined in their documentation:

https://docs.confluent.io/current/schema-registry/serdes-develop/index.html#sr-schemas-subject-name-strategy

The values are defined by the user so "foo" and "com.example" are as good as any other value.

All examples in following folder are runnable:
https://github.com/AbsaOSS/ABRiS/tree/master/src/main/scala/za/co/absa/abris/examples
