### ISSUE TITLE
Can I read multiple events of different record type from schema registry from a Single topic using ABRiS library ?

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/ABRiS#144]
Question from @vphutane: 

I am now testing the from_confluent_avro to read multiple events of different record types from the same ONE topic......before I proceed want to check with you is this possible. Can I read multiple events of different record type from schema registry from a Single topic using ABRiS library ?

**Comment by cerveada** [comment]
Well if there is the confluent schema id in the message Abris is able to use the schema and convert the message to spark dataframe, however different messages will have different schema and one Spark dataframe can have only one schema. So unless the schemas are compatible you need to separate the message before calling `from_confluent_avro` and then call it on each of them separately. Meaning you will have several groups each with only one schema. The final result will be one dataframe for each group.

**Comment by vphutane** [comment]
Thanks was able to retrieve messages from different record type from a single topic and created dataframe for individual record types successfully.
