### ISSUE TITLE
Cannot convert Catalyst type IntegerType to Avro type 

### ISSUE THREAD

**Issue by ottensjors** [AbsaOSS/ABRiS#146]
Hi team,

i'm loving ABRiS. however i do have a small question. i'm successfully able to use the function ```writeAvro()``` to generate a schema and new datarame ```avroser``` with column "value :binary" from dataframe ``` subdata  ``` based on dataframe ``` data ``` .

schema dataframe ``` data ```:
```
data.printSchema()
root
 |-- key: struct (nullable = true)
 |    |-- id: integer (nullable = false)
 |-- value: struct (nullable = true)
 |    |-- before: struct (nullable = true)
 |    |    |-- id: integer (nullable = false)
 |    |    |-- message_main_attachment_id: integer (nullable = true)
 |    |    |-- default_code: string (nullable = true)
 |    |    |-- active: boolean (nullable = true)
 |    |    |-- product_tmpl_id: integer (nullable = false)
 |    |    |-- barcode: string (nullable = true)
 |    |    |-- combination_indices: string (nullable = true)
 |    |    |-- volume: string (nullable = true)
 |    |    |-- weight: string (nullable = true)
 |    |    |-- can_image_variant_1024_be_zoomed: boolean (nullable = true)
 |    |    |-- create_uid: integer (nullable = true)
 |    |    |-- create_date: long (nullable = true)
 |    |    |-- write_uid: integer (nullable = true)
 |    |    |-- write_date: long (nullable = true)
 |    |-- after: struct (nullable = true)
 |    |    |-- id: integer (nullable = false)
 |    |    |-- message_main_attachment_id: integer (nullable = true)
 |    |    |-- default_code: string (nullable = true)
 |    |    |-- active: boolean (nullable = true)
 |    |    |-- product_tmpl_id: integer (nullable = false)
 |    |    |-- barcode: string (nullable = true)
 |    |    |-- combination_indices: string (nullable = true)
 |    |    |-- volume: string (nullable = true)
 |    |    |-- weight: string (nullable = true)
 |    |    |-- can_image_variant_1024_be_zoomed: boolean (nullable = true)
 |    |    |-- create_uid: integer (nullable = true)
 |    |    |-- create_date: long (nullable = true)
 |    |    |-- write_uid: integer (nullable = true)
 |    |    |-- write_date: long (nullable = true)
 |    |-- source: struct (nullable = false)
 |    |    |-- version: string (nullable = false)
 |    |    |-- connector: string (nullable = false)
 |    |    |-- name: string (nullable = false)
 |    |    |-- ts_ms: long (nullable = false)
 |    |    |-- snapshot: string (nullable = true)
 |    |    |-- db: string (nullable = false)
 |    |    |-- schema: string (nullable = false)
 |    |    |-- table: string (nullable = false)
 |    |    |-- txId: long (nullable = true)
 |    |    |-- lsn: long (nullable = true)
 |    |    |-- xmin: long (nullable = true)
 |    |-- op: string (nullable = false)
 |    |-- ts_ms: long (nullable = true)
 |    |-- transaction: struct (nullable = true)
 |    |    |-- id: string (nullable = false)
 |    |    |-- total_order: long (nullable = false)
 |    |    |-- data_collection_order: long (nullable = false)
```
creating dataframe ``` subdata ```:

```val subdata= data.select("key.id","value.after.default_code","value.after.write_date")```

with following schema:
```
subdata.printSchema()
root
 |-- id: integer (nullable = true)
 |-- default_code: string (nullable = true)
 |-- write_date: long (nullable = true)
```

followed by converting schema ```subdata``` into avro by means of ```writeAvro```:
```
avroser.printSchema()
root
 |-- value: binary (nullable = false)
```

which is all fine. the column ```value:binary``` has property ```nullable = false``` and i'm able to stream it to a new kafka topic.

in order to make use of the ```key``` and ```value``` with function ```to_confluent_avro()``` i managed to convert column ```id``` in dataframe ```subdata``` to ```nullable = false``` by using ```withColumn``` and ``` AssertNotNull ``` by creating column ```colleke``` and generating dataframe test2:

```val test2 = test.select(to_confluent_avro(col("colleke"), keyRegistryConfig) as 'key, to_confluent_avro(col("default_code"), valueRegistryConfig) as 'value)```

schema test2:
```
test2.printSchema()
root
 |-- key: binary (nullable = false)
 |-- value: binary (nullable = true)
```

afterwards i wrote the dataframe ```test2``` to kafka by utilizing ```writeStream``` but unfortunately i hit following error whilst the ```id``` column is of format ```binary``` and named ```key```:

```org.apache.spark.sql.avro.IncompatibleSchemaException: Cannot convert Catalyst type IntegerType to Avro type {"type":"record","name":"Key","namespace":"dbserver1.public.product_product","fields":[{"name":"id","type":"int"}],"connect.name":"dbserver1.public.product_product.Key"}```

any ideas? or am i just missing something here?

just let me know!

**Comment by cerveada** [comment]
It's all written in the exception. Your key (in spark) is integer, but in avro it's record containing integer. Record in avro == struct in Spark. So the type of the key should be `struct(integer)`

```
// not like that
val subdata= data.select("key.id","value.after.default_code","value.after.write_date")

// do this:
val subdata= data.select("id","value.after.default_code","value.after.write_date")
```
