### ISSUE TITLE
Improve Abris configuration

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/ABRiS#149]
Abris configuration is confusing right now. 
- Some option are used for both `toavro` and `fromavro`, but they mean something different
- some operation happens depending if something is present, but it's not really obvious. For example when the id is present the schema is loaded from the registry, but otherwise its generated.

It should be more obvious from the config what is going to happen and it ideally shouldn't allow you to use invalid config. My idea is something like this:
```
val config = AbrisConfig
  .toConfluentAvro
  .generateAndRegistrSchema(schemaRegistryUrl = "http://localhost:8081")
  .useRecordStrategy(name= "bar", namespace = "baz")
  .asKafkaKey
```

This would also allow simplification of the function to just `fromAvro` and `toAvro`, because everything else would be set in the configuration.

**Comment by felipemmelo** [comment]
Love this! I'm all in.
