### ISSUE TITLE
build jar

### ISSUE THREAD

**Issue by lingya** [AbsaOSS/ABRiS#153]
Where can I get it  

import io.confluent.kafka.serializers.subject.TopicNameStrategy
import io.confluent.kafka.serializers.subject.strategy.SubjectNameStrategy ?

**Comment by lingya** [comment]
fixed, can i consumer kafka0.10 by ABRiS 3.2.1?

**Comment by cerveada** [comment]
Yes, Abris is not really consuming form Kafka. That is doing Spark, Abris just converts the spark columns from and to avro format.
