### ISSUE TITLE
Cannot convert Catalyst type StringType to Avro type ["string","null"]

### ISSUE THREAD

**Issue by dgagneVets** [AbsaOSS/ABRiS#154]
I'm encountering this error on spark-3.0.0 on databricks:

`org.apache.spark.sql.avro.IncompatibleSchemaException: Cannot convert Catalyst type StringType to Avro type ["string","null"].
	at org.apache.spark.sql.avro.AvroSerializer.newConverter(AvroSerializer.scala:219)
	at org.apache.spark.sql.avro.AvroSerializer.$anonfun$newStructConverter$1(AvroSerializer.scala:239)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at org.apache.spark.sql.types.StructType.foreach(StructType.scala:102)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at org.apache.spark.sql.types.StructType.map(StructType.scala:102)
	at org.apache.spark.sql.avro.AvroSerializer.newStructConverter(AvroSerializer.scala:232)
	at org.apache.spark.sql.avro.AvroSerializer.newConverter(AvroSerializer.scala:193)
	at org.apache.spark.sql.avro.AvroSerializer.$anonfun$newStructConverter$1(AvroSerializer.scala:239)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at org.apache.spark.sql.types.StructType.foreach(StructType.scala:102)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at org.apache.spark.sql.types.StructType.map(StructType.scala:102)
	at org.apache.spark.sql.avro.AvroSerializer.newStructConverter(AvroSerializer.scala:232)
	at org.apache.spark.sql.avro.AvroSerializer.<init>(AvroSerializer.scala:72)
	at org.apache.spark.sql.avro.AvroSerializer.<init>(AvroSerializer.scala:55)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.serializer$lzycompute(CatalystDataToAvro.scala:44)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.serializer(CatalystDataToAvro.scala:43)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.nullSafeEval(CatalystDataToAvro.scala:49)`

it looks like even though the library is mostly compatible with spark 3.0.0, the maven build references spark-avro 2.4.4.  

Is ABRis compatible with a full spark 3.0.0 install? 

The Databricks platform has:
spark 3.0.0 (with spark-avro 3.0.0)
scala 2.12
avro v1.8.2
and pyspark 

I built an uber-jar using:
`mvn -P spark-3.0,uber,,scala-2.12 package`

and pushed that up to my spark cluster.
 
the pyspark code that calls abris through the spark context:
`
jvm_gateway = SparkContext._active_spark_context._gateway.jvm
    abris_avro = jvm_gateway.za.co.absa.abris.avro

    schema_registry_config_dict = {
        "schema.registry.url": schema_registry_url,
        "schema.registry.topic": topic,
        "{col}.schema.id".format(col=col): "latest",
        "{col}.schema.naming.strategy".format(col=col): "topic.name"
    }

    conf_map = getattr(getattr(jvm_gateway.scala.collection.immutable.Map, "EmptyMap$"), "MODULE$")
    for k, v in schema_registry_config_dict.items():
        conf_map = getattr(conf_map, "$plus")(jvm_gateway.scala.Tuple2(k, v))

    return Column(abris_avro.functions.to_confluent_avro(_to_java_column(col), conf_map))
`
I'm curious if there's any effort to make this work on spark-avro 3.0.0? I'm unable to replace spark-avro 3.0.0 with 2.4.4 on databricks, as this seems to cause spark to error out.  If I make the replacement in the maven config and run the tests, some of the tests fail, which makes me think the library is not fully compliant with a vanilla 3.0.0 spark installation.

(As a side note, I know this is not SO, but if anyone has been able to use ABRis to serialize confluent avro on Databricks, I would appreciate a link.)

**Comment by cerveada** [comment]
The StringType column must be nullable to match the Avro type ["string","null"]. Once you make the column nullable it should work on all supported Spark versions. (Or the other way around -> change avro type to just "string")

**Comment by dgagneVets** [comment]
> The StringType column must be nullable to match the Avro type ["string","null"]. Once you make the column nullable it should work on all supported Spark versions. (Or the other way around -> change avro type to just "string")
> 
> Please let me know if it works once you change the type.

When I change the type in the Confluent schema to just "string" (no union), I get a similar error:

Cannot convert Catalyst type StringType to Avro type ["string"].

I'm not sure whether avro type is getting misinterpreted as a union or if the string representation of the string type just looks like a union.  But either way, it looks like in the 3.0.0  spark-avro library AvroSerializer.newConverter is not finding a match for the provided catalyst and avro type and falls through to the default case.

**Comment by cerveada** [comment]
Spark DataFrames columns seems to be nullable by default. So that would mean the first schema was correct ["string","null"].

I wrote a simple test that is in PR linked above and it works even on Spark 3.0. You can check the automatic test in that PR.

**Comment by dgagneVets** [comment]
@cerveada - does that test still pass when you change the pom.xml like so?

` <profile>
            <id>spark-3.0</id>
            <properties>
                <spark.version>${spark-30.version}</spark.version>
                <spark.avro.version>${spark-30.version}</spark.avro.version>
            </properties>
        </profile>
`
The way I read it, you always run with the 2.4.4 version of spark-avro, which is at the root of my problem because in the 3.0.0 cluster environment I'm on, I can't force install spark-avro 2.4.4.

**Comment by dgagneVets** [comment]
> @cerveada - does that test still pass when you change the pom.xml like so?
> 
> `<profile> <id>spark-3.0</id> <properties> <spark.version>${spark-30.version}</spark.version> <spark.avro.version>${spark-30.version}</spark.avro.version> </properties> </profile>`
> The way I read it, you always run with the 2.4.4 version of spark-avro, which is at the root of my problem because in the 3.0.0 cluster environment I'm on, I can't force install spark-avro 2.4.4.

I apologize -- you're right that the error I quote in the subject is due to nullability in my spark schema.

**Comment by cerveada** [comment]
Can I close the ticket? Or do you still have some issues?

**Comment by dgagneVets** [comment]
Go ahead and close it. Thanks

**Comment by kevinwallimann** [comment]
For reference:

I've seen the same error message with the same root cause, i.e. the parquet column is non-nullable, whereas the corresponding avro field is nullable. However, in this example, the cause for the non-nullability might be non-obvious and is not visible in the printSchema.

```
    val mockSchemaRegistryClient = new AbrisMockSchemaRegistryClient()
    private val schemaRegistryConfig = Map(AbrisConfig.SCHEMA_REGISTRY_URL -> http://localhost:8081)
    SchemaManagerFactory.resetSRClientInstance()
    SchemaManagerFactory.addSRClientInstance(schemaRegistryConfig, mockSchemaRegistryClient)
    val spark = SparkSession.builder().getOrCreate()

    val schemaCatalyst = new StructType()
      .add("value1", LongType, nullable = true)
      .add("value2", IntegerType, nullable = true)
    val value1s = (1 to 100).map(_ => 42L)
    val value2s = (1 to 100).map(_ % 5)
    val rows = value1s.zip(value2s).map(a => Row(a._1, a._2))
    val input = new MemoryStream[Row](1, spark.sqlContext)(RowEncoder(schemaCatalyst))
    input.addData(rows)

    val df = input.toDF()
      .filter(col("value1") === lit(42))
    df.printSchema

    val allColumns = struct(df.columns.map(c => df(c)): _*)
    val avroSchema = toAvroType(allColumns.expr.dataType, allColumns.expr.nullable)
    println(avroSchema.toString(true))
    val schemaManager = SchemaManagerFactory.create(schemaRegistryConfig)
    val topic = "test-topic"
    val subject = SchemaSubject.usingTopicNameStrategy(topic, isKey = false)
    val schemaId = schemaManager.register(subject, avroSchema)
    val toAvroConfig = AbrisConfig
      .toConfluentAvro
      .downloadSchemaById(schemaId)
      .usingSchemaRegistry(schemaRegistryConfig)
    import za.co.absa.abris.avro.functions.to_avro
    val avroFrame = df.select(to_avro(allColumns, toAvroConfig) as 'value)

    val query = avroFrame
      .writeStream
      .trigger(Trigger.Once)
      .queryName("dummyQuery")
      .format("memory")
      .start()
    query.awaitTermination()
```

The output from `df.printSchema` is
```
root
 |-- value1: long (nullable = true)
 |-- value2: integer (nullable = true)
```
However, the query fails with 
```
org.apache.spark.sql.avro.IncompatibleSchemaException: Cannot convert Catalyst type LongType to Avro type ["long","null"].
	at org.apache.spark.sql.avro.AvroSerializer.newConverter(AvroSerializer.scala:197)
	at org.apache.spark.sql.avro.AvroSerializer.$anonfun$newStructConverter$1(AvroSerializer.scala:209)
```

The query succeeds when replacing
```
      .filter(col("value1") === lit(42))
```
with 
```
      .filter(col("value1") eqNullSafe lit(42))
```
In hindsight, this may make sense, since nullability is rather an optimization property to Spark, than a schema enforcement property. Indeed, the `EqualTo` operator extends the `NullIntolerant` trait (https://github.com/apache/spark/blob/branch-3.1/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/predicates.scala#L814-L815), which in turn is used to create `IsNotNull` constraints by the optimizer.

This has been tested with Spark 2.4.6 / Abris 4.2.0
Note that nullability mismatches between Catalyst schema and Avro schema has been relaxed in Spark 3.0 (https://issues.apache.org/jira/browse/SPARK-27838), so this particular exception should not be thrown anymore. Thus, this example succeeded with Spark 3.1.2 / Abris 4.2.0, but only after explicitly declaring the dependency to spark-avro 3.1.2, overriding the dependency to spark-avro 2.4.6 in Abris 4.2.0
