### ISSUE TITLE
Be less strict about nullable <--> non-nullable type conversions.

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/ABRiS#155]
- It makes sense to allow users to convert non-nullable type to nullable one.
- spark-avro even allows to convert nullable to non-nulable and fails only when null value is present. https://issues.apache.org/jira/browse/SPARK-27838

**Comment by JonDegn** [comment]
I agree. This is definitely a pain point for us.

**Comment by cerveada** [comment]
This is solved in Abris 5 by using spark-avro for conversions. When using Spark Avro 3+ it should work. Check the documentation for more info.
