### ISSUE TITLE
Add anotation to make clear what part of project are conisdered public API

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/ABRiS#159]
Something like @unstable to method that are public but not consider to be public API.

List on a per-file level:

### public API
```
avro.format.SparkAvroConversions
avro.parsing.utils.AvroSchemaUtils
avro.read.confluent.ConfluentConstants
avro.read.confluent.SchemaManager
avro.read.confluent.SchemaManagerFactory
avro.registry.AbrisMockSchemaRegistryClient
avro.registry.SchemaCoordinate
avro.registry.SchemaSubject
avro.registry.SchemaVersion
avro.functions
config.Config
```

### eventually will be private API
```
avro.format.ScalaAvroRecord
avro.format.ScalaSpecificData
avro.sql.AvroDataToCatalyst
avro.sql.AvroDeserializer
avro.sql.CatalystDataToAvro
avro.write.AvroWriterHolder
avro.write.ScalaCustomDatumWriter
avro.write.ScalaCustomSpecificData
```

`SparkAvroConversions` should keep available methods for converting between Spark <=> Avro schema, but the rest should probably be eventually private.

**Comment by kevinwallimann** [comment]
Another suggestion: `@DeveloperApi`, as seen in https://github.com/apache/spark/blob/master/common/tags/src/main/java/org/apache/spark/annotation/DeveloperApi.java

**Comment by cerveada** [comment]
Maybe the best solution would be to make anything that is not part of public API package private
```
private[abris]
```
https://alvinalexander.com/scala/how-to-control-scala-method-scope-object-private-package/

This could be done in next major release.

**Comment by cerveada** [comment]
Annotations are ready here:
https://github.com/AbsaOSS/commons/issues/70
