### ISSUE TITLE
Support Spark 2.4.0 and Schema Registry 5.0 Naming Strategies

### ISSUE THREAD

**Issue by redsk** [AbsaOSS/ABRiS#18]
Hi guys, first of all, thanks for your efforts!

Do you plan to update ABRiS to support Spark 2.4 and the new Schema Registry naming strategies?
Cheers

**Comment by felipemmelo** [comment]
Hey Nicola, how are you? Yes, we are definitely supporting those, however, it will take a bit more time. Probably by the end of jan19. 

Cheers.

**Comment by felipemmelo** [comment]
Hi Nicola, how are you? 

There is now support for other naming strategies from SR 5.0. Regarding Spark 2.4, I'll do that in a separate release. So, I'll take the freedom to close this issue and open another one specifically for supporting Spark 2.4. If you face any problems with the new release feel free to start another issue.

Cheers,

Felipe.
