### ISSUE TITLE
Getting schema-registry unauthorized even if im passing credentials

### ISSUE THREAD

**Issue by sivasai-quartic** [AbsaOSS/ABRiS#190]
I'm using abris 3.2.0 to connnect to schema-registry client to fetch the schema. Its actually working as expected while trying to run the code in the intellij.  But when I used spark-submit to run the jar, I'm getting 401 unauthorized error. Not sure, whether its including required dependencies.

```
val commonSchemaConfig: Map[String, String] = Map(
      SchemaManager.PARAM_SCHEMA_REGISTRY_URL -> schemaRegistryUrl,
      SchemaManager.PARAM_SCHEMA_REGISTRY_TOPIC -> topicName,
     "basic.auth.credentials.source" -> "URL") 

    val keySchemaConfig: Map[String, String] = Map(
      SchemaManager.PARAM_KEY_SCHEMA_NAMING_STRATEGY -> "topic.name",
      SchemaManager.PARAM_KEY_SCHEMA_ID -> "latest"
    ) ++ commonSchemaConfig

    val valueSchemaConfig: Map[String, String] = Map(
      SchemaManager.PARAM_VALUE_SCHEMA_NAMING_STRATEGY -> "topic.name",
      SchemaManager.PARAM_VALUE_SCHEMA_ID -> "latest"
    ) ++ commonSchemaConfig

    (keySchemaConfig, valueSchemaConfig)
```
did anyone faced this ? or am I missing some thing ?

**Comment by cerveada** [comment]
The schema-registry must be accessible from Spark driver and executors.

Since it works locally, something is probably blocking the access from the Spark cluster.

**Comment by sivasai-quartic** [comment]
actually running in local mode in command line same as in intellij. guess some dependency issue. one update is, I'm able to run in local mode by passing schema-registry client jar with `--jars` option.

**Comment by cerveada** [comment]
Were you able to make it work? 

As I already wrote if it works locally and not on the cluster and the error is `401 unauthorized error` it is a network issue. You must make sure the schema registry is reachable from the cluster.

It could also be wrong security config, but then it wouldn't work locally.
