### ISSUE TITLE
Avro schema with array fields not working.

### ISSUE THREAD

**Issue by vipul1409** [AbsaOSS/ABRiS#203]
Code generated using avro hugger library has avro array represented as List but when I am trying to write this to a kafka topic it is throwing "Not a union" error. 
Sample avro schema I am using, as per the sf question : https://stackoverflow.com/questions/9417732/optional-array-in-avro-schema
```
{
    "type":"record",
    "name":"test_avro",
    "fields":[{
            "name":"test_field_1",
            "type":"long"
        },
        {
            "name":"subrecord",
            "type":[{
                    "type":"record",
                    "name":"subrecord_type",
                    "fields":[{
                            "name":"field_1",
                            "type":"long"
                        }
                    ]
                },
                "null"
            ]
        },
        {
            "name":"simple_array",
            "type":["null",
                {
                    "type":"array",
                    "items":"string"
                }
            ],
            "default":null
        }
    ]
}
```

Am I missing something?

**Comment by cerveada** [comment]
Avro represents nullability as union of null and the actual type. So this might mean you are converting non-nullable column to nullable one or vice versa.

**Comment by vipul1409** [comment]
Thanks @cerveada I figured it out later that I had to specify even the array elements as union to make it work otherwise, even though the array is marked as null. May be there is a better way to fix this but just posting my idea for anyone else who comes across same issue.
