### ISSUE TITLE
How to access HTTPS version of SchemaRegistry

### ISSUE THREAD

**Issue by ravisunkara** [AbsaOSS/ABRiS#208]
I have been trying to build a scala structured streaming from kafka  using ABRIS for converting my  from_avro functionality
 <artifactId>abris_2.11</artifactId> <version>4.1.0</version> I am looking  to connect to HTTPS schema registry and right now i could not find a way to pass those parameters.

**Comment by cerveada** [comment]
How to pass parameters to a schema registry client is described here:
https://github.com/AbsaOSS/ABRiS#schema-registry-security-and-other-additional-settings
