### ISSUE TITLE
Error while runnin ABRiS for pyspark

### ISSUE THREAD

**Issue by masterappu** [AbsaOSS/ABRiS#211]
Hi,

I tried to add ABRiS to pyspark code with the following configurations
```
   .config("spark.jars.repositories","https://packages.confluent.io/maven/")\
   .config("spark.jars.packages","za.co.absa:abris_2.12:4.1.0") \
```

I am getting the following error code while i try to run the example pyspark [example ](https://github.com/AbsaOSS/ABRiS/blob/master/documentation/python-documentation.md)

`Exception in thread "main" java.lang.RuntimeException: [download failed: org.apache.zookeeper#zookeeper;3.4.14!zookeeper.jar, download failed: io.netty#netty;3.10.6.Final!netty.jar(bundle), download failed: com.fasterxml.jackson.core#jackson-annotations;2.9.10!jackson-annotations.jar(bundle)]`

I tried it with different versions of ABRiS, each time  a different jar issue is occurring.

**Comment by cerveada** [comment]
Hi,

sorry hard to tell what is the cause from this. Maybe you are behind some sort of firewall that is causing `download failed`?

**Comment by masterappu** [comment]
No. It is not due to firewall. I tried it with different versions and the package with error varies.

**Comment by cerveada** [comment]
To me, it seems Spark is for some reason not able to download the libraries named. Why is that is impossible to tell from the information here. 

As a workaround, you can try to create an Abris fat jar with all the libraries and provide that to Spark.

**Comment by cerveada** [comment]
@masterappu Will you able to solve the problem?

**Comment by masterappu** [comment]
I could not try the solution, may be we could close the issue
