### ISSUE TITLE
Schema Registry credentials should not be printed in the Spark plan

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/ABRiS#212]
Currently, schema registry credentials can be leaked in the spark plan, like this
![image](https://user-images.githubusercontent.com/54136196/114871267-69a87f80-9df9-11eb-89e6-10d929ca1ac9.png)

Obviously, this is a security risk.

The values of the specific keys containing passwords should be redacted, namely `schema.registry.basic.auth.user.info`, `basic.auth.user.info`, and `bearer.auth.token`. Another option is not to print the whole schema registry conf at all since arguably the schema registry config is not relevant for the analysis of the spark plan

**Comment by cerveada** [comment]
Is this a log in Abris? Or who is printing this?

**Comment by kevinwallimann** [comment]
I took the printscreen from the SQL tab of a streaming query in spark history. It's not a direct log in Abris, but I suspect that it's the default `toString` implementation of `FromAvroConfig` or sth like that
