### ISSUE TITLE
Upgrade deprecated usages of FlatSpec, Matchers

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/ABRiS#217]
With the upgrade to scalatest 3.1.0, `org.scalatest.FlatSpec` and `org.scalatest.Matchers` have been marked deprecated. According to the scaladoc, they should be replaced with `org.scalatest.flatspec.AnyFlatSpec` and `org.scalatest.should.Matchers`

**Comment by cerveada** [comment]
Fix as part of #256
