### ISSUE TITLE
Is Abris supposed to work with Spark 3.1.1?

### ISSUE THREAD

**Issue by hatharom** [AbsaOSS/ABRiS#221]
Description mentions only 3.0.x with avro v1.8.0 . 
Spark 3.1.1 brings in v1.9.2 (tried also with explicit 1.8.0 declaration and also with Abris 4.2.0/3.1.x), but can't get it to work.

I don't include my logs right now, it is just a general question : 
is Spark 3.1.x supported?

**Comment by kevinwallimann** [comment]
Hi @hatharom 
I have used Abris v4.2.0 with Spark 3.1.1, it should work. Looking at their pom file, I still see Spark 3.1.1 uses avro v1.8.0. Where did you see it uses avro v1.9.2?

**Comment by hatharom** [comment]
You right, I double checked , it is not 1.9.x, it is 1.8.0.
