### ISSUE TITLE
Value select is not a member of org.apache.spark.sql.streaming.DataStreamReader

### ISSUE THREAD

**Issue by DwijadasDey** [AbsaOSS/ABRiS#225]
Hi
I am trying to test abris 4.2.0 in a spark(3.1.1) shell and having an issue in the deserialization  step as given below.  The error is **"value select is not a member of org.apache.spark.sql.streaming.DataStreamReader"**

```
...
...

// Stream from Kafka
scala> val kafkaRead=spark.readStream
.format("kafka")
.option("kafka.bootstrap.servers", KAFKA_BOOTSTRAP_SERVERS_CONS)
.option("subscribe", KAFKA_TOPIC_NAME_CONS)
.option("kafka.security.protocol", "SSL")
.option("kafka.ssl.endpoint.identification.algorithm", "")
.option("kafka.ssl.truststore.location","C:\\ssl\\truststore.jks")
.option("kafka.ssl.truststore.password","Password123")
.option("kafka.ssl.keystore.location", "C:\\ssl\\keystore.jks")
.option("kafka.ssl.keystore.password","Password123")
.option("kafka.ssl.key.password","Password123")
.option("startingOffsets", "earliest").load()

scala> val abrisConfig=AbrisConfig
.fromConfluentAvro
.downloadReaderSchemaByLatestVersion
.andTopicNameStrategy(KAFKA_TOPIC_NAME_CONS,isKey=false)
.usingSchemaRegistry("http://kfk-sr1:8082")

scala> import za.co.absa.abris.avro.functions.from_avro
scala> val deserialized=kafkaRead.select(from_avro(col("value"), abrisConfig) as 'data)

val deserialized=kafkaRead.select(from_avro(col("value"), abrisConfig) as 'data)
<console>:35: error: value select is not a member of org.apache.spark.sql.streaming.DataStreamReader
 val deserialized=kafkaRead.select(from_avro(col("value"), abrisConfig) as 'data)
                                  ^
<console>:35: error: overloaded method value from_avro with alternatives:
(column: org.apache.spark.sql.Column,schema: String)org.apache.spark.sql.Column <and>
(column: org.apache.spark.sql.Column,config: za.co.absa.abris.config.FromAvroConfig)org.apache.spark.sql.Column
cannot be applied to (org.apache.spark.sql.Column, za.co.absa.abris.config.AbrisConfig.type)
       val deserialized=kafkaRead.select(from_avro(col("value"), abrisConfig) as 'data)
```
I don't see any member by the name select in the package org.apache.spark.sql.streaming.DataStreamReader

Can anyone please point out what am i doing wrong ?

Regards

**Comment by cerveada** [comment]
It looks a bit like you forgot to call the `.load()` method. Can you check what is the type of `kafkaRead` before you call the select?

**Comment by DwijadasDey** [comment]
The .load() method is called at the end 

```
...
...
.option("startingOffsets", "earliest").load()
```
The type of kafkaRead is `org.apache.spark.sql.streaming.DataStreamReader` and it looks it don't have the `select` method.

Ref: https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/streaming/DataStreamReader.html

I am trying to implement the example as in https://github.com/AbsaOSS/ABRiS/blob/master/src/main/scala/za/co/absa/abris/examples/ConfluentKafkaAvroReader.scala

Thanks

**Comment by cerveada** [comment]
But the load method should return `org.apache.spark.sql.DataFrame` not `DataStreamReader`

**Comment by DwijadasDey** [comment]
Yes, You are right. kafkaRead is of type dataframe (org.apache.spark.sql.DataFrame)

`res13: org.apache.spark.sql.DataFrame = [key: binary, value: binary ... 5 more fields]`

But then in the spark shell pressing tabs after `kafkaRead.` does not shows the `select` method.

```
scala> kafkaRead.
!=   ->             csv        equals      getClass       json   notify      options   schema         text       wait   
##   ==             ensuring   format      hashCode       load   notifyAll   orc       synchronized   textFile   â      
+    asInstanceOf   eq         formatted   isInstanceOf   ne     option      parquet   table          toString  

```

**Comment by DwijadasDey** [comment]
Hi
I am able to implement the same using `Spark-3.0.2/Abris 4.2.0`. Don't know why the above code has not worked in `Spark-3.1.1`
