### ISSUE TITLE
FromAvroConfig class is not serializable

### ISSUE THREAD

**Issue by yokhan-dukhin** [AbsaOSS/ABRiS#228]
I am using spark structured streaming with "foreach" sink. To get that work the class FromAvroConfig needs to be serializable.
The fix should be simple, the class just needs to be extended from Serializable (tested locally, works fine).

**Comment by cerveada** [comment]
Yes, that makes sense. Adding Serializable should not break backward compatibility. It would be good to do the same thing for `ToAvroConfig`.

Since you already tested that it works, will you have a time to do a Pull Request for this?

**Comment by yokhan-dukhin** [comment]
Thanks, I just have created a PR #229.
This is my 1st commit/PR in github, so please let me know if I did something wrong.
