### ISSUE TITLE
Improve exceptions during schema register 

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/ABRiS#230]
Function [register(subject: SchemaSubject, schema: Schema)](https://github.com/AbsaOSS/ABRiS/blob/dd9e07be9caa2e68d73c54de27a74266edb0e71b/src/main/scala/za/co/absa/abris/avro/read/confluent/SchemaManager.scala#L74) SchemaManager.scala 
The exception could be thrown only if a schema is not compatible and an error message should be more clearer and state only that.

**Comment by cerveada** [comment]
I agree that the Error message could be better.

The `Schema does not exist` is not error, though. The exception is thrown if and only if the schema for the subject already exists and at the same time it is not compatible with the schema that you're trying to register.

I think reversing the if statement would make the code clearer.

The exceptions from `schemaRegistryClient` are not covered by this exception at all. At least that's what I see in the code.

**Comment by jozefbakus** [comment]
Yes, you are right, I've changed the issue.
