### ISSUE TITLE
Create new abris version that will support Spark 3.2 (also Avro 1.10 and confluent 6.2.0) 

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/ABRiS#239]
The current version will stay available for Spark version < 3.2

**Comment by wundi** [comment]
We have code changes and a Spark 3.2.0 build for this (using Avro 1.10.2, Confluent 6.2.1). Due to changes in Spark, the `AvroDataToCatalyst` and `CatalystDataToAvro` classes needs to override a new `withNewChildInternal` method, which becomes an issue when simultaneously supporting Spark 3.2 and older versions.

I'm not strong in Scala, so there might be a way around it. I'll happily make our changes public and do a PR for you to look through, if you want?

**Comment by cerveada** [comment]
@wundi yes please, that would be great. 

To have one Abris that works with all Spark versions would be nice, but It may cause a lot of otherwise unnecessary changes for the library. But I will think about it.

**Comment by cerveada** [comment]
More context for `withNewChildInternal` method:
https://github.com/apache/spark/commit/0945baf90660a101ae0f86a39d4c91ca74ae5ee3

**Comment by wundi** [comment]
I have created to PRs, in order to separate the Spark compatibility discussion from the other changes. 
#244 upgrades Avro and Confluent platform and can be merged in isolation. 
#245 furthers on #244 and upgrades to Spark 3.2.0 but introduces changes incompatible with Spark 3.1 and older.

**Comment by cerveada** [comment]
Thank you. I already have something partially implemented, so I will probably not use the PR directly, but it's helpful to see what already works and is tested.

**Comment by wundi** [comment]
That's completely fair - use what you can and feel free to close the PRs (or I can do so as well?). Happy to be of help. We've recently adopted Spark and had Confluent platform already, so ABRiS was a great help to our productivity. It's only fair to try and give something back if we can.

**Comment by redsk** [comment]
@cerveada is the support for Spark 3.2 complete? If this is the case, would you consider a new release?

**Comment by cerveada** [comment]
@redsk mostly it is. We will release that version in January, but feel free to build it yourself from the master branch if you want to try it sooner.

**Comment by redsk** [comment]
@cerveada I did and it worked fine for me. But of course we would need a local repository for fetching this dependency, and it's a bit cumbersome for us atm.

**Comment by cerveada** [comment]
ABRiS 6.0.0 was released.
