### ISSUE TITLE
Support Spark 2.4

### ISSUE THREAD

**Issue by felipemmelo** [AbsaOSS/ABRiS#25]

**Comment by ljodea** [comment]
Hi @felipemmelo

Just wanted to say you guys did an amazing job with this. Bravo!

Is there anything we can do to help get this ready for Spark 2.4.0?

**Comment by felipemmelo** [comment]
Hi @ljodea , thanks a lot!

So, the project was started to solve a simple case, but then grew to become a library. 

The API is currently implemented [here](https://github.com/AbsaOSS/ABRiS/blob/master/src/main/scala/za/co/absa/abris/avro/AvroSerDe.scala) and [here](https://github.com/AbsaOSS/ABRiS/blob/master/src/main/scala/za/co/absa/abris/avro/AvroSerDeWithKeyColumn.scala).

We would like, as you mentioned, to make it similar to [this](https://databricks.com/blog/2018/11/30/apache-avro-as-a-built-in-data-source-in-apache-spark-2-4.html). In that, we could extend it to also support `from_confluent_avro`, `to_confluent_avro` and both of these with Schema Registry configurations as a parameter. Even more than that, we would like to make this library seamlessly interchangeable with the one provided by Spark 2.4. This way, if users are using Spark directly but have the need to play with Confluent Kafka and/or Schema Registry, they could simply import ABRiS and everything should work the same.

I have just checked what you've done [here](https://github.com/ljodea/confluent-spark-avro), and the idea of encoding/decoding only the columns of interest is exactly what we need.

So, answering directly to your question, all the blocks are there (Schema Registry connectors, Confluent decoders, etc), and the only thing we need to do is to change the API referred to above to something similar to what you did. Thus, if you would like to join us and contribute, it would be very welcome! And of course, we would be entirely available to help.

Cheers!

**Comment by cerveada** [comment]
Spark 2.4 avro functions are supported from version 3.0.0.
