### ISSUE TITLE
Error deserializing Number type column without precision nor scala - Oracle

### ISSUE THREAD

**Issue by joserivera1990** [AbsaOSS/ABRiS#294]
Hello everyone,

I'm working in a project with Confluent with the Kafka Connect connector CDC Oracle and The connector serialized with io.confluent.connect.avro.AvroConverter. The problem is that in some tables Oracle there are some fields with Number Type without precision or scale, for this reason the Schema registry is created in this way:

    {
      "name": "TEST_NUMBER",
      "type": [
        "null",
        {
          "type": "bytes",
          "scale": 127,
          "precision": 64,
          "connect.version": 1,
          "connect.parameters": {
            "scale": "127"
          },
          "connect.name": "org.apache.kafka.connect.data.Decimal",
          "logicalType": "decimal"
        }
      ],
      "default": null
    }

When I use the library abris_2.12 version 5.1.1 with Spark 3.1.2 to deserialize data, the fields with Number type without precision or scale are shown with bytes and no as decimal.

![image](https://user-images.githubusercontent.com/16911323/166648635-91bc041b-3aa4-4150-841c-d62df90f7dae.png)

¿Do you know if this library supported this feature? ¿Should I configure anything more?
¿Do you know If It's is mind to develop that feature?
    

Code:
```Scala
val abrisConfig = AbrisConfig
  .fromConfluentAvro
  .downloadReaderSchemaByLatestVersion
  .andTopicNameStrategy(topic)
  .usingSchemaRegistry(propsAvro)

def saveToDBFinal = (df: Dataset[Row], batchId: Long) => {

  df.show(false)
  
  val df2 = df.select(from_avro(col("value"), abrisConfig) as "data").selectExpr("data.*")
  df2.show(false)
}  
```

Thanks for your answer

Regards

**Comment by cerveada** [comment]
Hello,

Could you print `d2.schema()` and post it here?

What version of `org.apache.spark:spark-avro` library is on your classpath?

**Comment by joserivera1990** [comment]
> Hello,
> 
> Could you print `d2.schema()` and post it here?
> 
> What version of `org.apache.spark:spark-avro` library is on your classpath?

Hi @cerveada,

I added the print to `d2.schema()`
StructType(StructField(STFAMPRO,StringType,true), StructField(CHFAMPRO,StringType,true), **StructField(TEST_NUMBER,BinaryType,true)**, StructField(TEST_NUMBER_DECIMAL,BinaryType,true), StructField(table,StringType,true), StructField(SCN_CMD,StringType,true), StructField(OP_TYPE_CMD,StringType,true), StructField(op_ts,StringType,true), StructField(current_ts,StringType,true), StructField(row_id,StringType,true), StructField(username,StringType,true))

Checking the external libraries I have -> org.apache.spark:spark-avro_2.12:2.4.8

Regards.

**Comment by joserivera1990** [comment]
> Hi @joserivera1990 Unfortunately, your avro schema is invalid. Per the avro spec, "Scale must be [...] less than or equal to the precision.", see https://avro.apache.org/docs/current/spec.html#Decimal, which is not the case (127 > 64). What happens is that the logical type (Decimal) is not validated when the schema is parsed and instead falls back to null. So, Spark doesn't see the avro logical type decimal and interprets it as a BinaryType instead of a DecimalType.
> 
> To solve the issue, you could
> 
> * fix the schema generation process
> * or change the avro schema on schema registry
> * or provide the fixed reader schema to Abris using the `.provideReaderSchema` config method (see https://github.com/AbsaOSS/ABRiS/blob/master/documentation/confluent-avro-documentation.md#avro-to-spark for examples)

Hi @kevinwallimann,

I got your points, about changing the schema generation process, this schema is generated by Confluent on the connector CDC Oracle
https://docs.confluent.io/kafka-connect-oracle-cdc/current/troubleshooting.html#numeric-data-type-with-no-precision-or-scale-results-in-unreadable-output 

I did the test using the function `.provideReaderSchema` and setting in the schema the values: precicion:38 and scale:10 

 `{\"name\":\"TEST_NUMBER\",\"type\":[\"null\",{\"type\":\"bytes\",\"scale\":10,\"precision\":38,\"connect.version\":1,\"connect.parameters\":{\"scale\":\"10\"},\"connect.name\":\"org.apache.kafka.connect.data.Decimal\",\"logicalType\":\"decimal\"}],\"default\":null}`

And throw the next error: `Decimal precision 128 exceeds max precision 38`

Finally, I think that should have some way to get the number with scale of 127 and precicion of 64, I don't know if as a string in place of decimal. Por example, I'm using the connector `com.snowflake.kafka.connector.SnowflakeSinkConnector` and in the properties in value.converter `io.confluent.connect.avro.AvroConverter` In the Snowflake DataBase that row is saved in this way:
```
{
  "STFAMPRO": "AA",
  "TEST_NUMBER": "5.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "TEST_NUMBER_DECIMAL": "5.1500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "current_ts": "1651059748133",
}
```
The problem is than I don't know as Snowflake implements this connector com.snowflake.kafka.connector.SnowflakeSinkConnector

Thanks for your time!
