### ISSUE TITLE
Fix JaCoCo CI for PRs from forked repos

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/ABRiS#329]
Fix JaCoCo CI for PRs from forked repos

[Enabling workflows for forks of private repositories](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories)

[Assigning permissions to jobs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)

**Comment by cerveada** [comment]
Was fixed in PR #334
