### ISSUE TITLE
Detect different schema versions in batch

### ISSUE THREAD

**Issue by talperetz1** [AbsaOSS/ABRiS#336]
Hi, I have a question regarding using abris.
I have a spark stream that read from kafka topic parse the avro message using Abris and then write it.
I wanted to know if in each micro-batch when I read from kafka I can detect if I have two messages with the same schema but different version. For example lets says I added an optional filed to the schema and release newer version and now I have in the topic some "old" messages with the old schema and new messages with the new schema that consumed in the same micro batch

**Comment by cerveada** [comment]
Abris is able to detect the version of writer schema and change the values according to newer schema version specified (reader schema). Like using default value for new field in the newer schema. You define the reader schema when you call Abris.

**Comment by cerveada** [comment]
Well, Abris detects the wrtiter schema Id here:
 https://github.com/AbsaOSS/ABRiS/blob/7dea3faba2e1397cbed6b6e66fb3138b7a623274/src/main/scala/za/co/absa/abris/avro/sql/AvroDataToCatalyst.scala#L144

There is no mechanism to give this information to the user. It just tries to convert the data to reader schema and it will be successful if these two schemas are compatible.

Some ideas:
- You can read the id yourself and detect the changes.

- There is also an error handler in Abris that will allow you to react to failed records, but that may be too late for you.

**Comment by talperetz1** [comment]
Sorry but what is exactly this buffer?

**Comment by cerveada** [comment]
Look into the linked source code to see more.

The schema id is part of the confluent avro format
https://github.com/AbsaOSS/ABRiS#confluent-avro-format
