### ISSUE TITLE
malformed records to topic

### ISSUE THREAD

**Issue by talperetz1** [AbsaOSS/ABRiS#345]
I have a streams that consumes avro messages from kafka topic perform from_avro by the provided schema and write the dataframe to s3.
There is a possibility that in some point a an avro message with incompatible schema will arrive to my topic,
when that happens I will get Malformed record. Now I dont wnat to ignore this message and skip to the next and "correct" messages, I want to take that malformed record and write it to a topic/s3 bucket with his "malformed schema".
There is a wat to do so?
Thank you?

**Comment by cerveada** [comment]
Error handling is described her:
https://github.com/AbsaOSS/ABRiS#de-serialisation-error-handling

If the options available there are not sufficient for your use case, you can implement a custom error handler.

**Comment by talperetz1** [comment]
Thank you
