### ISSUE TITLE
foreach batch download by schem id

### ISSUE THREAD

**Issue by talperetz1** [AbsaOSS/ABRiS#347]
Is it possible in spark stream foreach batch when reading from kafka to extract the schema id, download with abris by schema id and then performed from_avro on my value column to generate the dataframe?

**Comment by cerveada** [comment]
If you talk about multiple compatible schemas in one topic (that is schema evolution basically) then that is supported by Abris out of the box.

If you talk about multiple incompatible schemas in one topic, that is not supported. You could work around this by manually sorting rows by confluent id to separated data frames and after that run Abris on each of them separately.

It is the same idea described here: https://github.com/AbsaOSS/ABRiS#multiple-schemas-in-one-topic

**Comment by luisvicenteatprima** [comment]
@cerveada by tha

> If you talk about multiple compatible schemas in one topic (that is schema evolution basically) then that is supported by Abris out of the box.

By this you mean using the latest version of the schema or something similar, don't you?

**Comment by cerveada** [comment]
https://docs.confluent.io/cloud/current/sr/fundamentals/schema-evolution.html
