### ISSUE TITLE
Use ABRiS on multiple topics

### ISSUE THREAD

**Issue by mxolisiz** [AbsaOSS/ABRiS#35]
Hi,

I'm a beginner in Scala development & big data streaming. I see most of your examples show how to read & de-serialize from one topic, does the library support multiple topics? or will I have to find a way to do that.
Thank you.

**Comment by felipemmelo** [comment]
Hi @mxolisiz , if the topics have the same schema, it should work. You can separate the topics by using `RETAIN_ORIGINAL_SCHEMA` as explained [here](https://github.com/AbsaOSS/ABRiS#usage)

If you however want to read topics containing different schemas, then it should not work from a limitation on Spark Structured Streams, as the schema for the dataframes needs to be defined before the job is started.

**Comment by mxolisiz** [comment]
Hi @felipemmelo  thanks for the response
"as the schema for the dataframes needs to be defined before the job is started" That makes sense thank you... I am reading from more than one topic which all have different schemas

Stupid question :) - does that mean if i want to use this library with my multiple topics & multiple schemas I'd probably have to read each topic to it's own separate dataframe and have separate schemaRegistryConfs (if writing that type of code in a clean way is possible)

**Comment by felipemmelo** [comment]
For multiple topics with multiple schemas, you'll need multiple jobs, even if only using Spark Structured Streams directly.

However, if you're using TopicNameStrategy (as in [here](https://docs.confluent.io/current/schema-registry/serializer-formatter.html)) for Schema Regsitry, you can reuse the configuration and only change the topic name, as the schema name will defined from the topic, as explained [here](https://github.com/AbsaOSS/ABRiS#reading-avro-binary-records-from-kafka-as-spark-structured-streams-loading-schema-from-schema-registry-and-performing-regular-sql-queries-on-them).

**Comment by mxolisiz** [comment]
@felipemmelo Oh ok, Thanks a lot for the assistance. learnt a lot here.
