### ISSUE TITLE
scalac: error while loading <root> 

### ISSUE THREAD

**Issue by karthit** [AbsaOSS/ABRiS#36]
Hi, 
im using scala 2.11 version and spark 2.4.3, 
while running the project im getting this error, 

Error:scalac: error while loading <root>, Error accessing /home/dev/.m2/repository/io/confluent/kafka-avro-serializer/5.1.0/kafka-avro-serializer-5.1.0.jar

Please help to resolve this,

**Comment by felipemmelo** [comment]
hi @karthit ,

It does not seem to be related to the library as it is failing to access a dependency. Some possibilities:

1. Confluent has their own Maven repo which is [this](https://github.com/AbsaOSS/ABRiS/blob/master/pom.xml#L31). Maybe you're running behind a proxy or something that is blocking it?

2. Maybe the dependency was successfully downloaded but cannot be accessed for some reason. Have you checked if `/home/dev/.m2/repository/io/confluent/kafka-avro-serializer/5.1.0/kafka-avro-serializer-5.1.0.jar` is actually there?

3. Some other issue that would require some context to analyse. Can you share a larger portion of the error stack?

**Comment by karthit** [comment]
@felipemmelo thanks for the help, my proxy is blocking confluent maven repository.

**Comment by premmnit** [comment]
@karthit - I am getting same issue , may I know how to unblock it via proxy?
