### ISSUE TITLE
`fromConfluentAvro` with RETAIN_ORIGINAL_SCHEMA not printing property/key names

### ISSUE THREAD

**Issue by chasdevs** [AbsaOSS/ABRiS#40]
Hello! I'm attempting to use this with confluent schema registry hosted on aiven.io, and I have everything working (using my PR [here](https://github.com/AbsaOSS/ABRiS/pull/39)), but my output when using RETAIN_ORIGINAL_SCHEMA only contains the values of my record, not the keys/properties.

For example, sending a record (registered in schema registry) with:
```json
{
  "meta": {
    "uuid": "uuid: 0.9538...",
    "emitted": "156484..."
  },
  "x": 3,
  "y": 5.0,
  "foo": null
}
```
yields
```
+----+----------------------------------------------------+-------------+---------+------+-----------------------+-------------+
|key |value                                               |topic        |partition|offset|timestamp              |timestampType|
+----+----------------------------------------------------+-------------+---------+------+-----------------------+-------------+
|null|[[uuid: 0.9538167490250689, 1564849980152], 3, 5.0,]|example-event|0        |0     |2019-08-03 12:33:01.307|0            |
+----+----------------------------------------------------+-------------+---------+------+-----------------------+-------------+
```

**Comment by chasdevs** [comment]
Note that when I use RETAIN_SELECTED_COLUMN_ONLY, it yields:
```
+-----------------------------------------+---+---+----+
|meta                                     |x  |y  |foo |
+-----------------------------------------+---+---+----+
|[uuid: 0.9538167490250689, 1564849980152]|3  |5.0|null|
+-----------------------------------------+---+---+----+
```

**Comment by felipemmelo** [comment]
Hi @chasdevs , foremost, thank you VERY much for the PR, will get into that tomorrow.

Regarding your question, just to be sure, are you using the API that supports keys, such as explained [here](https://github.com/AbsaOSS/ABRiS#writingreading-keys-and-values-as-avro-tofrom-kafka)?

Also, if you print your Dataframe without decoding it from Avro, can you see the `key` as something other than `null`?

Cheers.

**Comment by chasdevs** [comment]
@felipemmelo thanks for getting back to me so quickly. Turns out I was just being dumb since I'm new to spark streaming. The behavior works as expected; I just assumed my record-within-a-record example was not printing correctly. Closing.
