### ISSUE TITLE
java.util.NoSuchElementException: key not found: schema.name with TOPIC_NAME strategy

### ISSUE THREAD

**Issue by tonyclyde** [AbsaOSS/ABRiS#57]
Using the following config which I thought should not require a `schema.name` to be set, but getting the below error anyway.

```  
val commonRegistryConfig: Map[String, String] = Map(
        SchemaManager.PARAM_SCHEMA_REGISTRY_URL -> SchemaRegistryUrl,
        SchemaManager.PARAM_SCHEMA_REGISTRY_TOPIC -> OutputTopic
    )
    
  val keyRegistryConfig: Map[String, String] = commonRegistryConfig +
    (
        SchemaManager.PARAM_KEY_SCHEMA_NAMING_STRATEGY -> SchemaManager.SchemaStorageNamingStrategies.TOPIC_NAME,
        SchemaManager.PARAM_VALUE_SCHEMA_ID -> "latest")

  val valueRegistryConfig: Map[String, String] = commonRegistryConfig +
    (
        SchemaManager.PARAM_VALUE_SCHEMA_NAMING_STRATEGY -> SchemaManager.SchemaStorageNamingStrategies.TOPIC_NAME,
        SchemaManager.PARAM_VALUE_SCHEMA_ID -> "latest")
```

```
java.util.NoSuchElementException: key not found: schema.name
at scala.collection.MapLike$class.default(MapLike.scala:228)
at scala.collection.AbstractMap.default(Map.scala:59)
at scala.collection.MapLike$class.apply(MapLike.scala:141)
at scala.collection.AbstractMap.apply(Map.scala:59)
at za.co.absa.abris.avro.functions$.to_confluent_avro(functions.scala:140)
```

**Comment by cerveada** [comment]
When the schema is generated automatically, these values are used for schema name and namespace.

I guess Abris could provide some default value, so you doesn't have to provide those.

For now you can just provide those values in the configuration.

**Comment by tonyclyde** [comment]
That makes sense, thanks!

Then Im probably just not doing things right. Im trying to use the existing `<topic>-key` and `<topic>-value` schemas that are already in the registry for the given topic but cant seem to find the right configuration to do so. I tried setting `SchemaManager.PARAM_SCHEMA_NAME_FOR_RECORD_STRATEGY` to `key` and `value` respectively (which i think is the confluent default) but that gives me these errors:

```
java.security.InvalidParameterException: Schema could not be registered for topic '<topic>'. Make sure that the Schema Registry is available, the parameters are correct and the schemas ar compatible
```

Any guidance appreciated. Thanks.

**Comment by cerveada** [comment]
The idea was that when you write avro you also write the schema to registry and when you read avro you read the schema from there.

So to_confluent_avro will generate the schema and try to register it, the generated and the schema already in register are not compatible and that's the reason why it fails.

**Comment by cerveada** [comment]
I would try to load the schema first ```AvroSchemaUtils.loadForValue(schemaRegistryConf)``` and then call ```to_confluent_avro``` with the provided schema.

**Comment by tonyclyde** [comment]
Thanks for your help, this seems to mostly work but then Im back to being blocked by #58  

```
to_confluent_avro(
                col("key"),
                AvroSchemaUtils.loadForKey(keyRegistryConfig).toString,
                keyRegistryConfig
            )
```

For now Im just falling back on serializing and sending my messages manually via the `KafkaProducer` but will come back to this once thats resolved.

Thanks!
