### ISSUE TITLE
Issue while calling pyspark

### ISSUE THREAD

**Issue by sparkheo7** [AbsaOSS/ABRiS#66]
Hi , I am trying to deserlize kafka data through pyspark. But I am getting below error.

{TypeError}Invalid argument, not a string or column: from_avro(value) AS `data` of type <class 'py4j.java_gateway.JavaObject'>. For column literals, use 'lit', 'array', 'struct' or 'create_map' function.
environment 
pyspark :- 2.4.3
abris version :- za.co.absa:abris_2.11:3.0.2

Code base for same is as below 

from pyspark.sql.dataframe import DataFrame
import logging, traceback
from confluent_kafka import Consumer as kafka_Consumer, KafkaError, TopicPartition
import time
import requests
from pyspark.sql import functions as F
from pyspark.sql import DataFrame, Column
from pyspark.sql.functions import udf

def deserialize_avro1(spark_context, sql_context, data_frame, schema_registry_url, topic):
        j = spark_context._gateway.jvm
        naming_strategy = getattr(
            getattr(j.za.co.absa.abris.avro.read.confluent.SchemaManager,
                    "SchemaStorageNamingStrategies$"), "MODULE$").TOPIC_NAME()
        logger.info("SchemaStorageNamingStrategy: for topic " + topic + " is " + str(naming_strategy))
        conf = getattr(getattr(j.scala.collection.immutable.Map, "EmptyMap$"), "MODULE$")
        conf = getattr(conf, "$plus")(j.scala.Tuple2("schema.registry.url", schema_registry_url))
        conf = getattr(conf, "$plus")(j.scala.Tuple2("schema.registry.topic", topic))
        conf = getattr(conf, "$plus")(j.scala.Tuple2("value.schema.id", "latest"))
        conf = getattr(conf, "$plus")(j.scala.Tuple2("value.schema.naming.strategy", naming_strategy))
                    
        data_frame.select(j.za.co.absa.abris.avro.functions.from_confluent_avro(data_frame._jdf.col("value"), conf).alias("data")).select("data.*")

Can you please help in addressing this. or let me know if I am missing anything over here.

**Comment by felipemmelo** [comment]
Hi @sparkheo7 , could you maybe create a simple example that does not Schema Registry so that we can try to reproduce the issue?

**Comment by sparkheo7** [comment]
Here you go. Still getting same error

[deserialize_avro_json.zip](https://github.com/AbsaOSS/ABRiS/files/3687589/deserialize_avro_json.zip)

**Comment by sparkheo7** [comment]
Hi @felipemmelo,
As we are calling it from pyspark, it's returning jcol.  I converted it by unwrapping it with Column class. I will update readme with pyspark example. Thanks again for looking into it. I am closing this issue.
