### ISSUE TITLE
Where is the 2.0.0 version of ABRiS?

### ISSUE THREAD

**Issue by sanori** [AbsaOSS/ABRiS#7]
In https://github.com/AbsaOSS/ABRiS#maven-dependency , you recommend version 2.0.0.
But, in http://mvnrepository.com/artifact/za.co.absa/abris , there are versions of 0.0.1 and 1.0.0.
How can I get 2.0.0 version of ABRiS?

**Comment by felipemmelo** [comment]
Hey Joo-Won, it is here: https://mvnrepository.com/artifact/za.co.absa/abris/2.0.0

I published it yesterday thus there probably was a delay between your search and Maven Central sync.

**Comment by sanori** [comment]
I found it! Thank you!
![image](https://user-images.githubusercontent.com/5754657/43312960-b3c3fd40-91c9-11e8-8273-84193b35b601.png)
