### ISSUE TITLE
updated readme with scala example for read/write avro (json encoding) with confluent schema registry

### ISSUE THREAD

**Issue by xavtx1** [AbsaOSS/ABRiS#73]
I dont found documentation about how to read and write, against Confluent Kafka and Schema registry, for messages avro with json enconding, only for avro with binary encoding.

https://avro.apache.org/docs/1.8.1/spec.html#json_encoding

**Comment by felipemmelo** [comment]
Hi @xavtx1 

We currently only support binary encoding as we haven't yet found a use case to justify also supporting Json. Could you provide some more details on the requirements?

Cheers.

**Comment by xavtx1** [comment]
Hi @felipemmelo Currently we are being sent the data from the source with avro json coding, we do not have the possibility change that and one of the reasons why the data is sent to us in this format is because elsewhere in the pipeline we are informed that it is more appropriate for debugging tasks.

**Comment by felipemmelo** [comment]
hi @xavtx1 , sorry for the delay, we've been through a public holiday.

Unfortunately, right now we are busy working on other priorities thus we won't have time to add this feature too soon. However, if you'd like to get involved in the project and maybe submit a PR, we'd be more than happy to review it.

Cheers.

**Comment by felipemmelo** [comment]
Closing for maintenance reasons. Feel free to reopen if needed.
