### ISSUE TITLE
PARAM_SCHEMA_ID? typo of PARAM_VALUE_SCHEMA_ID?

### ISSUE THREAD

**Issue by sanori** [AbsaOSS/ABRiS#8]
In [README.md](https://github.com/AbsaOSS/ABRiS/blob/master/README.md#reading-avro-binary-records-from-confluent-platform-using-schema-registry-as-spark-structured-streams-and-performing-regular-sql-queries-on-them):
```scala
   SchemaManager.PARAM_SCHEMA_ID             -> "latest" // otherwise, just specify an id
```
But there is no `PARAM_SCHEMA_ID` in SchemaManager ([Reference](https://github.com/AbsaOSS/ABRiS/blob/master/src/main/scala/za/co/absa/abris/avro/read/confluent/SchemaManager.scala#L39-L43))

**Comment by felipemmelo** [comment]
You're right, Joo-Won, the schemas are now separated for key and value. Will update the documentation and let you know asap. Thanks for the support.
