### ISSUE TITLE
Question about `AvroDataToCatalyst. decodeConfluentAvro ` behavior

### ISSUE THREAD

**Issue by donsokolone** [AbsaOSS/ABRiS#93]
I'd like to ask if providing schema id / "latest" when doing Confluent Avro is really necessary?

In https://github.com/AbsaOSS/ABRiS/blob/master/src/main/scala/za/co/absa/abris/avro/sql/AvroDataToCatalyst.scala#L104 it's required to provide reader schema. 

But when you inspect Confluent Avro deserializer you stumble upon this https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java#L190-L195 which seems to use writer schema for reader schema whenever reader schema is not provided.

Reason why I'm asking about this is that I do not want to tell my spark streaming jobs which reader schema it should use (via providing schema id or "latest") because I'd like to use schema id that is embedded into Confluent Avro payload itself.

**Comment by felipemmelo** [comment]
Hi @donsokolone ,

Thanks for the question.

The issue with getting the id from the top of the payload is related to Spark needing to know the schema upfront to create the Dataframe encoders. If you have messages with different schemas, you won't be able to deserialise them into a Dataframe and even if you were, writing computations that test for the existence or not of a field might be cumbersome. 

Could you share more details on your use case and why specifying a reader schema upfront is not desirable?

Cheers.

**Comment by donsokolone** [comment]
Thanks @felipemmelo for detailed explanation!
I have had some "exotic" requirements that seem to be invalidated at the moment :) 

This lib is awesome and you guys are doing awesome work. Kudos!

**Comment by felipemmelo** [comment]
Thanks @donsokolone! 

So I'll be closing the issue for now but feel free to reopen it at any time.

Cheers.
