### ISSUE TITLE
Previous record information pulled to next record for null columns 

### ISSUE THREAD

**Issue by ramvalasa** [AbsaOSS/ABRiS#94]
Did anyone faced any issue of previous record information getting pulled to current record in case of null columns using from_confluent_avro method. Source team is stating the avro pushed doesn't contain the those information, however when the method is used the previous record information is being populated for current record.

**Comment by felipemmelo** [comment]
Hi @ramvalasa , thanks for reporting.

Could you please suggest a way to replicate the problem? Maybe a code snippet?

Cheers.

**Comment by ramvalasa** [comment]
Hi @felipemmelo , Just ran some tests to replicate the scenario, found the source producer had some issues. This issue is not valid. Thanks for the help!
