### ISSUE TITLE
ABRiS 3.x possible with Spark 2.3.0?

### ISSUE THREAD

**Issue by solarmicrobe** [AbsaOSS/ABRiS#95]
As of #48 ABRiS now requires spark 2.4.4.  Is there something inherent that needs this version?  I'm trying to use ABRiS, and specifically to_avro.  I'm bound by my hadoop cluster distribution at 2.3.0 and when testing locally, if I go from ABRiS 2.2.4 to 3.x my local run goes to spark 2.4.x.  
Adding exclusions to try and get back to 2.3.0 I'm getting an error
> Exception in thread "main" java.lang.IllegalAccessError: tried to access method org.apache.spark.util.EventLoop.eventThread()Ljava/lang/Thread; from class org.apache.spark.sql.internal.SQLConf$$anonfun$14
I'm pretty sure that's related to my exclusions but now I'm not sure about how to get this to work with 2.3.0.  Any suggestions?

**Comment by cerveada** [comment]
Hello,
There is known (and solvable) problem with Avro dependency. Please read: https://github.com/AbsaOSS/ABRiS#supported-spark-versions

**Comment by cerveada** [comment]
I'm closing this since it seems to be solved. Feel free to reopen if you still have a problem.
